// Comprehensive in-memory store for standalone demo / serverless hosting without database dependency
export interface Category {
  id: string;
  name: string;
  slug: string;
  icon: string | null;
  image: string | null;
  description: string | null;
  _count?: { products: number };
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  price: number;
  mrp: number;
  stock: number;
  unit: string;
  imageUrl: string;
  badge: string | null;
  isFeatured: boolean;
  isVegetarian: boolean;
  brand: string | null;
  categoryId: string;
  category?: Category;
  createdAt: Date;
  updatedAt: Date;
}

export interface Customer {
  id: string;
  name: string;
  email: string | null;
  phone: string;
  password?: string | null;
  address: string | null;
  city: string;
  pincode: string;
  points: number;
  createdAt: Date;
}

export interface OrderItem {
  id: string;
  orderId: string;
  productId: string | null;
  productName: string;
  productImage: string;
  price: number;
  quantity: number;
  unit: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  customerId: string | null;
  customerName: string;
  customerPhone: string;
  customerAddress: string;
  status: string;
  paymentMethod: string;
  paymentStatus: string;
  subtotal: number;
  deliveryFee: number;
  discount: number;
  total: number;
  deliverySlot: string;
  notes: string | null;
  items: OrderItem[];
  customer?: Customer | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Coupon {
  id: string;
  code: string;
  discountPercent: number;
  minOrderAmount: number;
  maxDiscount: number;
  description: string | null;
  isActive: boolean;
  createdAt: Date;
}

export interface InventoryLog {
  id: string;
  productId: string;
  productName: string;
  changeAmount: number;
  type: string;
  reason: string | null;
  createdAt: Date;
}

// Global store singleton that persists across API calls in the same serverless instance
class Store {
  categories: Category[] = [
    {
      id: "cat-1",
      name: "Atta, Flours & Sooji",
      slug: "atta-flours-sooji",
      icon: "Wheat",
      image: "/images/products/pohsan_maida.jpg",
      description: "Pohsan maida, crispy sooji, Aashirvaad chakki atta, besan and multigrain flours.",
    },
    {
      id: "cat-2",
      name: "Dals & Pulses",
      slug: "dals-pulses",
      icon: "Sparkles",
      image: "/images/products/tata_toor_dal.jpg",
      description: "Tata Sampann unpolished Toor, Moong, Chana, Masoor, and Kabuli Chana.",
    },
    {
      id: "cat-3",
      name: "Rice & Grains",
      slug: "rice-grains",
      icon: "Layers",
      image: "/images/products/india_gate_rice.jpg",
      description: "India Gate Feast Rozzana Basmati rice, Daawat super basmati, and poha.",
    },
    {
      id: "cat-4",
      name: "Edible Oils & Ghee",
      slug: "edible-oils-ghee",
      icon: "Droplet",
      image: "/images/products/bail_kolhu_oil.jpg",
      description: "Bail Kolhu Kacchi Ghani Mustard Oil, refined sunflower oil, and Amul pure cow ghee.",
    },
    {
      id: "cat-5",
      name: "Spices & Masalas",
      slug: "spices-masalas",
      icon: "Flame",
      image: "/images/products/everest_garam_masala.jpg",
      description: "Everest Garam Masala, MDH Deggi Mirch, Tata Salt, and whole blended spices.",
    },
    {
      id: "cat-6",
      name: "Dairy & Breakfast",
      slug: "dairy-breakfast",
      icon: "Coffee",
      image: "/images/products/amul_butter.jpg",
      description: "Amul pasteurized butter, cow ghee, toned milk, cheese slices, oats and breakfast cereals.",
    },
    {
      id: "cat-7",
      name: "Snacks & Beverages",
      slug: "snacks-beverages",
      icon: "GlassWater",
      image: "/images/products/sprite_bottle.jpg",
      description: "Chilled Sprite, Haldiram's Bhujia Sev, Maggi noodles, Lay's chips, and Tata tea.",
    },
    {
      id: "cat-8",
      name: "Personal Care & Cleaning",
      slug: "personal-care-cleaning",
      icon: "Sparkle",
      image: "/images/products/impact_wash.jpg",
      description: "Impact Wash detergent powder, Surf Excel, Vim gel, Dettol antiseptic, and soaps.",
    },
  ];

  products: Product[] = [];
  customers: Customer[] = [];
  orders: Order[] = [];
  coupons: Coupon[] = [];
  inventoryLogs: InventoryLog[] = [];

  constructor() {
    this.initData();
  }

  private initData() {
    const now = new Date();

    this.coupons = [
      {
        id: "c-1",
        code: "WELCOME100",
        discountPercent: 15,
        minOrderAmount: 499,
        maxDiscount: 100,
        description: "Get 15% OFF up to ₹100 on your first grocery order!",
        isActive: true,
        createdAt: now,
      },
      {
        id: "c-2",
        code: "SUPERKIRANA",
        discountPercent: 20,
        minOrderAmount: 999,
        maxDiscount: 250,
        description: "Super Market Special: 20% OFF up to ₹250 on orders above ₹999",
        isActive: true,
        createdAt: now,
      },
      {
        id: "c-3",
        code: "FREESHIP",
        discountPercent: 10,
        minOrderAmount: 299,
        maxDiscount: 50,
        description: "Instant ₹50 savings on any delivery in Naugarh / Tetari Bazar",
        isActive: true,
        createdAt: now,
      },
    ];

    this.customers = [
      {
        id: "cust-1",
        name: "Rajesh Verma",
        phone: "9838012345",
        password: "123456",
        email: "rajesh.verma@example.com",
        address: "House 42, Tetari Bazar Main Road",
        city: "Naugarh",
        pincode: "272207",
        points: 50,
        createdAt: now,
      },
      {
        id: "cust-2",
        name: "Pooja Srivastava",
        phone: "9792067890",
        password: "123456",
        email: "pooja.sri@example.com",
        address: "Plot 18, Rahul Nagar, Near Grocery For All",
        city: "Naugarh",
        pincode: "272207",
        points: 50,
        createdAt: now,
      },
    ];

    this.products = [
      {
        id: "prod-1",
        name: "Sprite Cold Drink Bottle",
        slug: "sprite-bottle-750ml",
        description: "Clear, crisp lemon-lime sparkling refreshing cold soda drink, served chilled.",
        price: 40,
        mrp: 45,
        stock: 180,
        unit: "750 ml",
        imageUrl: "/images/products/sprite_bottle.jpg",
        badge: "Chilled Special",
        isFeatured: true,
        isVegetarian: true,
        brand: "Coca-Cola",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-2",
        name: "Haldiram's Nagpur Bhujia Sev",
        slug: "haldirams-bhujia-sev-400g",
        description: "Crispy spiced moth bean flour noodle snack seasoned with authentic Indian herbs and spices.",
        price: 110,
        mrp: 125,
        stock: 140,
        unit: "400 g",
        imageUrl: "/images/products/haldirams_bhujia.jpg",
        badge: "Tea-Time Snack",
        isFeatured: true,
        isVegetarian: true,
        brand: "Haldiram's",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-3",
        name: "Maggi 2-Minute Masala Instant Noodles",
        slug: "maggi-masala-noodles-4pack",
        description: "Favorite classic instant noodles with the authentic aroma of roasted spices and herbs.",
        price: 56,
        mrp: 60,
        stock: 220,
        unit: "Pack of 4 (280 g)",
        imageUrl: "/images/products/maggi_noodles.svg",
        badge: "All-Time Favorite",
        isFeatured: true,
        isVegetarian: true,
        brand: "Nestle",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-4",
        name: "Lay's India's Magic Masala Potato Chips",
        slug: "lays-magic-masala-chips-50g",
        description: "Crispy crinkled potato chips infused with a blend of spicy, tangy Indian masalas.",
        price: 20,
        mrp: 20,
        stock: 160,
        unit: "50 g Pack",
        imageUrl: "/images/products/lays_chips.svg",
        badge: "Popular Snack",
        isFeatured: false,
        isVegetarian: true,
        brand: "Lay's",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-5",
        name: "Tata Tea Gold Leaf & Dust Blend",
        slug: "tata-tea-gold-500g",
        description: "Exquisite blend of fine Assam tea leaves with gently rolled 15% long leaves for rich aroma.",
        price: 295,
        mrp: 340,
        stock: 90,
        unit: "500 g",
        imageUrl: "/images/products/tata_tea_gold.svg",
        badge: "Rich Taste",
        isFeatured: true,
        isVegetarian: true,
        brand: "Tata Tea",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-6",
        name: "Cadbury Dairy Milk Silk Chocolate Bar",
        slug: "cadbury-dairy-milk-silk-150g",
        description: "Smoother, creamier, and melt-in-mouth milk chocolate bar for sweet celebrations.",
        price: 175,
        mrp: 185,
        stock: 85,
        unit: "150 g",
        imageUrl: "/images/products/cadbury_silk.svg",
        badge: "Sweet Treat",
        isFeatured: false,
        isVegetarian: true,
        brand: "Cadbury",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-7",
        name: "Parle-G Gold Glucose Biscuits Mega Pack",
        slug: "parle-g-gold-biscuits-1kg",
        description: "Bigger, crisper, and richer glucose biscuits, trusted across millions of Indian homes.",
        price: 90,
        mrp: 100,
        stock: 130,
        unit: "1 kg Pack",
        imageUrl: "/images/products/parle_g.svg",
        badge: "Daily Chai Companion",
        isFeatured: false,
        isVegetarian: true,
        brand: "Parle",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-8",
        name: "Frooti Fresh Mango Drink",
        slug: "frooti-mango-drink-1-2l",
        description: "Made from real ripe Totapuri mangoes, delicious thirst-quenching refreshing mango drink.",
        price: 65,
        mrp: 75,
        stock: 110,
        unit: "1.2 L Bottle",
        imageUrl: "/images/products/frooti.svg",
        badge: "Refreshing",
        isFeatured: false,
        isVegetarian: true,
        brand: "Parle Agro",
        categoryId: "cat-7",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-9",
        name: "Amul Butter (Pasteurized)",
        slug: "amul-butter-500g",
        description: "Utterly butterly delicious creamy salted table butter made from fresh dairy milk.",
        price: 275,
        mrp: 290,
        stock: 65,
        unit: "500 g",
        imageUrl: "/images/products/amul_butter.jpg",
        badge: "Breakfast Star",
        isFeatured: true,
        isVegetarian: true,
        brand: "Amul",
        categoryId: "cat-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-10",
        name: "Amul Taaza Homogenised Toned Milk",
        slug: "amul-taaza-toned-milk-1l",
        description: "Pure and fresh toned milk with 3.0% fat, sterilized and packed in tamper-proof aseptic pack.",
        price: 72,
        mrp: 75,
        stock: 95,
        unit: "1 L Tetra Pack",
        imageUrl: "/images/products/amul_taaza_milk.svg",
        badge: "Fresh Dairy",
        isFeatured: true,
        isVegetarian: true,
        brand: "Amul",
        categoryId: "cat-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-11",
        name: "Amul Processed Cheese Slices",
        slug: "amul-cheese-slices-200g",
        description: "10 individually wrapped delicious creamy processed cheese slices for sandwiches and burgers.",
        price: 140,
        mrp: 155,
        stock: 70,
        unit: "10 Slices (200 g)",
        imageUrl: "/images/products/amul_cheese.svg",
        badge: "Kids Favorite",
        isFeatured: false,
        isVegetarian: true,
        brand: "Amul",
        categoryId: "cat-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-12",
        name: "Quaker Rolled White Oats",
        slug: "quaker-rolled-oats-1kg",
        description: "100% whole grain nutritious breakfast oats, high in dietary fiber to support heart health.",
        price: 185,
        mrp: 220,
        stock: 55,
        unit: "1 kg Pouch",
        imageUrl: "/images/products/quaker_oats.svg",
        badge: "Healthy Choice",
        isFeatured: false,
        isVegetarian: true,
        brand: "Quaker",
        categoryId: "cat-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-13",
        name: "Kellogg's Real Almond & Honey Corn Flakes",
        slug: "kelloggs-corn-flakes-almond-honey-475g",
        description: "Crispy golden corn flakes enriched with real Californian almonds and sweet floral honey.",
        price: 245,
        mrp: 285,
        stock: 45,
        unit: "475 g Box",
        imageUrl: "/images/products/kelloggs_cornflakes.svg",
        badge: "Crunchy Breakfast",
        isFeatured: false,
        isVegetarian: true,
        brand: "Kellogg's",
        categoryId: "cat-6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-14",
        name: "Impact Wash Premium Detergent Powder",
        slug: "impact-wash-detergent-2kg",
        description: "Advanced active enzyme formula that removes tough collar stains while keeping clothes vibrant.",
        price: 199,
        mrp: 240,
        stock: 85,
        unit: "2 kg Pack",
        imageUrl: "/images/products/impact_wash.jpg",
        badge: "In-Store Banner Deal",
        isFeatured: true,
        isVegetarian: true,
        brand: "Impact Wash",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-15",
        name: "Surf Excel Easy Wash Detergent Powder",
        slug: "surf-excel-easy-wash-1kg",
        description: "Formulated with 10 hands power to effortlessly wash dirt and curry stains in minutes.",
        price: 145,
        mrp: 160,
        stock: 120,
        unit: "1 kg Pack",
        imageUrl: "/images/products/surf_excel.svg",
        badge: "Top Seller",
        isFeatured: true,
        isVegetarian: true,
        brand: "Surf Excel",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-16",
        name: "Vim Lemon Dishwash Gel Bottle",
        slug: "vim-lemon-dishwash-gel-750ml",
        description: "Concentrated gel with 100 lemons power, degreases oily pots and stainless steel utensils effortlessly.",
        price: 135,
        mrp: 155,
        stock: 90,
        unit: "750 ml Bottle",
        imageUrl: "/images/products/vim_gel.svg",
        badge: "Kitchen Care",
        isFeatured: false,
        isVegetarian: true,
        brand: "Vim",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-17",
        name: "Harpic Power Plus 10X Toilet Cleaner",
        slug: "harpic-power-plus-1l",
        description: "Thick blue liquid formula eliminates 99.9% germs, limescale, and tough yellowish stains.",
        price: 180,
        mrp: 205,
        stock: 75,
        unit: "1 L Bottle",
        imageUrl: "/images/products/harpic.svg",
        badge: "Hygiene Shield",
        isFeatured: false,
        isVegetarian: true,
        brand: "Harpic",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-18",
        name: "Dettol Original Antiseptic Disinfectant Liquid",
        slug: "dettol-antiseptic-liquid-550ml",
        description: "Trusted germ protection for first aid, wound cleaning, personal hygiene, and laundry sanitizer.",
        price: 195,
        mrp: 220,
        stock: 80,
        unit: "550 ml Bottle",
        imageUrl: "/images/products/dettol.svg",
        badge: "Doctor Recommended",
        isFeatured: false,
        isVegetarian: true,
        brand: "Dettol",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-19",
        name: "Colgate MaxFresh Peppermint Ice Gel Toothpaste",
        slug: "colgate-maxfresh-peppermint-150g",
        description: "Infused with cooling crystals for 10x longer lasting fresh breath and cavity protection.",
        price: 98,
        mrp: 110,
        stock: 140,
        unit: "150 g Pack",
        imageUrl: "/images/products/colgate.svg",
        badge: "Fresh Breath",
        isFeatured: false,
        isVegetarian: true,
        brand: "Colgate",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-20",
        name: "Dove Cream Beauty Bathing Soap (3-Pack)",
        slug: "dove-cream-beauty-soap-300g",
        description: "Enriched with 1/4th moisturizing cream to nourish dry skin soft and glowing.",
        price: 165,
        mrp: 190,
        stock: 65,
        unit: "3 x 100 g Bars",
        imageUrl: "/images/products/dove_soap.svg",
        badge: "Gentle Care",
        isFeatured: false,
        isVegetarian: true,
        brand: "Dove",
        categoryId: "cat-8",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-21",
        name: "Everest Garam Masala",
        slug: "everest-garam-masala-100g",
        description: "Celebrated blend of 13 aromatic Indian spices to give curries their rich royal aroma.",
        price: 88,
        mrp: 96,
        stock: 150,
        unit: "100 g",
        imageUrl: "/images/products/everest_garam_masala.jpg",
        badge: "Essential",
        isFeatured: true,
        isVegetarian: true,
        brand: "Everest",
        categoryId: "cat-5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-22",
        name: "MDH Deggi Mirch (Kashmiri Blend)",
        slug: "mdh-deggi-mirch-100g",
        description: "Produces deep crimson red gravy color with balanced mild pleasant spiciness.",
        price: 92,
        mrp: 100,
        stock: 130,
        unit: "100 g",
        imageUrl: "/images/products/mdh_deggi_mirch.jpg",
        badge: "Hot Deal",
        isFeatured: true,
        isVegetarian: true,
        brand: "MDH",
        categoryId: "cat-5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-23",
        name: "Tata Salt Vacuum Evaporated Iodized Salt",
        slug: "tata-salt-iodized-1kg",
        description: "India's most trusted pure white iodized salt for daily mental and physical wellness.",
        price: 26,
        mrp: 28,
        stock: 250,
        unit: "1 kg Pack",
        imageUrl: "/images/products/tata_salt.svg",
        badge: "Daily Essential",
        isFeatured: true,
        isVegetarian: true,
        brand: "Tata",
        categoryId: "cat-5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-24",
        name: "Kissan Fresh Tomato Ketchup",
        slug: "kissan-tomato-ketchup-950g",
        description: "100% real juicy vine-ripened tomatoes made into sweet and tangy family sauce.",
        price: 125,
        mrp: 145,
        stock: 85,
        unit: "950 g Squeezy Bottle",
        imageUrl: "/images/products/kissan_ketchup.svg",
        badge: "Family Pack",
        isFeatured: false,
        isVegetarian: true,
        brand: "Kissan",
        categoryId: "cat-5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-25",
        name: "Catch Black Pepper Table Sprinkler",
        slug: "catch-black-pepper-sprinkler-100g",
        description: "Coarsely ground Malabar black pepper in a convenient rotating tabletop shaker.",
        price: 85,
        mrp: 95,
        stock: 60,
        unit: "100 g Can",
        imageUrl: "/images/products/catch_pepper.svg",
        badge: "Pungent Aroma",
        isFeatured: false,
        isVegetarian: true,
        brand: "Catch",
        categoryId: "cat-5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-26",
        name: "Bail Kolhu Kacchi Ghani Mustard Oil",
        slug: "bail-kolhu-mustard-oil-1l",
        description: "100% pure cold-pressed sarson tel with authentic pungent punch and natural antioxidants.",
        price: 148,
        mrp: 170,
        stock: 140,
        unit: "1 L Bottle",
        imageUrl: "/images/products/bail_kolhu_oil.jpg",
        badge: "Naugarh Favorite",
        isFeatured: true,
        isVegetarian: true,
        brand: "Bail Kolhu",
        categoryId: "cat-4",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-27",
        name: "Amul Pure Cow Ghee",
        slug: "amul-pure-cow-ghee-1l",
        description: "Rich, granular golden cow ghee made from fresh cream, offering traditional aroma and flavor.",
        price: 610,
        mrp: 650,
        stock: 55,
        unit: "1 L Tin",
        imageUrl: "/images/products/amul_pure_ghee.jpg",
        badge: "Pure & Fresh",
        isFeatured: true,
        isVegetarian: true,
        brand: "Amul",
        categoryId: "cat-4",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-28",
        name: "Fortune Sunlite Refined Sunflower Oil",
        slug: "fortune-sunflower-oil-1l",
        description: "Light, healthy, and easy-to-digest refined cooking oil enriched with Vitamin A and D.",
        price: 135,
        mrp: 155,
        stock: 110,
        unit: "1 L Pouch",
        imageUrl: "/images/products/fortune_sunflower_oil.svg",
        badge: "Heart Healthy",
        isFeatured: false,
        isVegetarian: true,
        brand: "Fortune",
        categoryId: "cat-4",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-29",
        name: "Tata Sampann Unpolished Toor Dal",
        slug: "tata-sampann-unpolished-toor-dal-1kg",
        description: "Rich in natural protein, delicious unpolished arhar dal with no artificial polish or coloring.",
        price: 168,
        mrp: 195,
        stock: 110,
        unit: "1 kg",
        imageUrl: "/images/products/tata_toor_dal.jpg",
        badge: "15% OFF",
        isFeatured: true,
        isVegetarian: true,
        brand: "Tata Sampann",
        categoryId: "cat-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-30",
        name: "Premium Yellow Moong Dal (Dhuli)",
        slug: "premium-yellow-moong-dal-1kg",
        description: "Quick cooking, light and wholesome yellow split moong dal, thoroughly cleaned.",
        price: 135,
        mrp: 155,
        stock: 75,
        unit: "1 kg",
        imageUrl: "/images/products/moong_dal.svg",
        badge: null,
        isFeatured: false,
        isVegetarian: true,
        brand: "Tata Sampann",
        categoryId: "cat-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-31",
        name: "Desi Chana Dal Unpolished",
        slug: "desi-chana-dal-1kg",
        description: "Sweet and nutty chana dal, high dietary fiber, perfect for puran poli and tadka dal.",
        price: 115,
        mrp: 130,
        stock: 65,
        unit: "1 kg",
        imageUrl: "/images/products/chana_dal.svg",
        badge: null,
        isFeatured: false,
        isVegetarian: true,
        brand: "Tata Sampann",
        categoryId: "cat-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-32",
        name: "Tata Sampann Organic Kabuli Chana",
        slug: "tata-sampann-kabuli-chana-1kg",
        description: "Large, uniform white chickpeas perfect for rich Punjabi chole and Amritsari bhature.",
        price: 155,
        mrp: 180,
        stock: 70,
        unit: "1 kg",
        imageUrl: "/images/products/tata_kabuli_chana.svg",
        badge: "Punjabi Chole Special",
        isFeatured: false,
        isVegetarian: true,
        brand: "Tata Sampann",
        categoryId: "cat-2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-33",
        name: "India Gate Basmati Rice Feast Rozzana",
        slug: "india-gate-basmati-rice-5kg",
        description: "Aromatic, long grain basmati rice specially aged for daily festive dining and biryanis.",
        price: 440,
        mrp: 520,
        stock: 60,
        unit: "5 kg",
        imageUrl: "/images/products/india_gate_rice.jpg",
        badge: "Super Saver",
        isFeatured: true,
        isVegetarian: true,
        brand: "India Gate",
        categoryId: "cat-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-34",
        name: "Daawat Super Basmati Rice",
        slug: "daawat-super-basmati-rice-1kg",
        description: "Slender and pearly grains with distinct aroma, expands up to 2.5 times when cooked.",
        price: 165,
        mrp: 190,
        stock: 85,
        unit: "1 kg",
        imageUrl: "/images/products/daawat_rice.svg",
        badge: null,
        isFeatured: false,
        isVegetarian: true,
        brand: "Daawat",
        categoryId: "cat-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-35",
        name: "Tata Sampann High Fiber Thick Poha",
        slug: "tata-sampann-thick-poha-500g",
        description: "Hygienically flattened paddy flakes that make fluffy, non-sticky morning kanda batata poha.",
        price: 48,
        mrp: 55,
        stock: 120,
        unit: "500 g",
        imageUrl: "/images/products/tata_poha.svg",
        badge: "Quick Breakfast",
        isFeatured: false,
        isVegetarian: true,
        brand: "Tata Sampann",
        categoryId: "cat-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-36",
        name: "Premium California Crunchy Almonds (Badam)",
        slug: "california-badam-almonds-500g",
        description: "100% natural, whole crunchy Californian almonds rich in Vitamin E, magnesium, and proteins.",
        price: 460,
        mrp: 550,
        stock: 50,
        unit: "500 g Pouch",
        imageUrl: "/images/products/california_badam.svg",
        badge: "Brain Power",
        isFeatured: true,
        isVegetarian: true,
        brand: "Grocery For All Select",
        categoryId: "cat-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-37",
        name: "Whole W240 King Cashew Nuts (Kaju)",
        slug: "king-cashew-nuts-kaju-500g",
        description: "Jumbo, whole white cashews with rich buttery taste, ideal for kheer, sweets, and snacking.",
        price: 490,
        mrp: 590,
        stock: 45,
        unit: "500 g Pouch",
        imageUrl: "/images/products/king_kaju.svg",
        badge: "Premium Quality",
        isFeatured: false,
        isVegetarian: true,
        brand: "Grocery For All Select",
        categoryId: "cat-3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-38",
        name: "Pohsan Fine Maida",
        slug: "pohsan-fine-maida-1kg",
        description: "Super fine wheat flour ideal for crispy samosas, bhature, cakes, and bakery delicacies.",
        price: 45,
        mrp: 52,
        stock: 120,
        unit: "1 kg",
        imageUrl: "/images/products/pohsan_maida.jpg",
        badge: "In-Store Favorite",
        isFeatured: true,
        isVegetarian: true,
        brand: "Pohsan",
        categoryId: "cat-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-39",
        name: "Pohsan Crispy Sooji (Rawa)",
        slug: "pohsan-crispy-sooji-500g",
        description: "Premium granular semolina for delicious halwa, upma, and crispy idli/dosa batter.",
        price: 35,
        mrp: 40,
        stock: 95,
        unit: "500 g",
        imageUrl: "/images/products/pohsan_sooji.jpg",
        badge: "Best Seller",
        isFeatured: true,
        isVegetarian: true,
        brand: "Pohsan",
        categoryId: "cat-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-40",
        name: "Aashirvaad Shudh Chakki Atta",
        slug: "aashirvaad-shudh-chakki-atta-5kg",
        description: "100% pure whole wheat flour processed with traditional chakki grinding for extra soft rotis.",
        price: 245,
        mrp: 275,
        stock: 80,
        unit: "5 kg",
        imageUrl: "/images/products/aashirvaad_atta.jpg",
        badge: "Top Value",
        isFeatured: true,
        isVegetarian: true,
        brand: "Aashirvaad",
        categoryId: "cat-1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "prod-41",
        name: "Fortune Pure Chana Besan",
        slug: "fortune-chana-besan-500g",
        description: "Finely ground pure gram flour for crispy pakoras, sweets, kadhi, and savoury delicacies.",
        price: 58,
        mrp: 68,
        stock: 85,
        unit: "500 g",
        imageUrl: "/images/products/fortune_besan.svg",
        badge: null,
        isFeatured: false,
        isVegetarian: true,
        brand: "Fortune",
        categoryId: "cat-1",
        createdAt: now,
        updatedAt: now,
      },
    ];

    // Populate category relations on products
    this.products.forEach((p) => {
      p.category = this.categories.find((c) => c.id === p.categoryId);
    });

    // Populate initial demo order
    this.orders = [
      {
        id: "order-1",
        orderNumber: "GFA-8021",
        customerId: "cust-1",
        customerName: "Rajesh Verma",
        customerPhone: "9838012345",
        customerAddress: "House 42, Tetari Bazar Main Road, Naugarh - 272207",
        status: "DELIVERED",
        paymentMethod: "UPI",
        paymentStatus: "PAID",
        subtotal: 1040,
        deliveryFee: 0,
        discount: 100,
        total: 940,
        deliverySlot: "Morning (9 AM - 11 AM)",
        notes: "Please call upon arrival at gate.",
        createdAt: new Date(Date.now() - 3600000 * 2),
        updatedAt: new Date(Date.now() - 3600000 * 2),
        items: [
          {
            id: "item-1",
            orderId: "order-1",
            productId: "prod-40",
            productName: "Aashirvaad Shudh Chakki Atta",
            productImage: "/images/products/aashirvaad_atta.jpg",
            price: 245,
            quantity: 2,
            unit: "5 kg",
          },
          {
            id: "item-2",
            orderId: "order-1",
            productId: "prod-26",
            productName: "Bail Kolhu Kacchi Ghani Mustard Oil",
            productImage: "/images/products/bail_kolhu_oil.jpg",
            price: 148,
            quantity: 2,
            unit: "1 L Bottle",
          },
          {
            id: "item-3",
            orderId: "order-1",
            productId: "prod-29",
            productName: "Tata Sampann Unpolished Toor Dal",
            productImage: "/images/products/tata_toor_dal.jpg",
            price: 168,
            quantity: 1,
            unit: "1 kg",
          },
          {
            id: "item-4",
            orderId: "order-1",
            productId: "prod-1",
            productName: "Sprite Cold Drink Bottle",
            productImage: "/images/products/sprite_bottle.jpg",
            price: 40,
            quantity: 2,
            unit: "750 ml",
          },
        ],
      },
    ];

    this.inventoryLogs = [
      {
        id: "log-1",
        productId: "prod-40",
        productName: "Aashirvaad Shudh Chakki Atta",
        changeAmount: 80,
        type: "RESTOCK",
        reason: "Initial Store Setup",
        createdAt: now,
      },
      {
        id: "log-2",
        productId: "prod-26",
        productName: "Bail Kolhu Kacchi Ghani Mustard Oil",
        changeAmount: 140,
        type: "RESTOCK",
        reason: "Initial Store Setup",
        createdAt: now,
      },
    ];
  }
}

// Global instance to survive hot-reloads and serverless invocations
const globalForStore = globalThis as unknown as {
  mockStore: Store | undefined;
};

export const mockDb = globalForStore.mockStore ?? new Store();
if (process.env.NODE_ENV !== "production") {
  globalForStore.mockStore = mockDb;
}
