import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database with 100% unique, distinct supermarket product images...");

  // Clean existing data
  await prisma.inventoryLog.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.coupon.deleteMany({});
  await prisma.product.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.customer.deleteMany({});

  // 1. Categories
  const categoriesData = [
    {
      name: "Atta, Flours & Sooji",
      slug: "atta-flours-sooji",
      icon: "Wheat",
      image: "/images/products/pohsan_maida.jpg",
      description: "Pohsan maida, crispy sooji, Aashirvaad chakki atta, besan and multigrain flours.",
    },
    {
      name: "Dals & Pulses",
      slug: "dals-pulses",
      icon: "Sparkles",
      image: "/images/products/tata_toor_dal.jpg",
      description: "Tata Sampann unpolished Toor, Moong, Chana, Masoor, and Kabuli Chana.",
    },
    {
      name: "Rice & Grains",
      slug: "rice-grains",
      icon: "Layers",
      image: "/images/products/india_gate_rice.jpg",
      description: "India Gate Feast Rozzana Basmati rice, Daawat super basmati, and poha.",
    },
    {
      name: "Edible Oils & Ghee",
      slug: "edible-oils-ghee",
      icon: "Droplet",
      image: "/images/products/bail_kolhu_oil.jpg",
      description: "Bail Kolhu Kacchi Ghani Mustard Oil, refined sunflower oil, and Amul pure cow ghee.",
    },
    {
      name: "Spices & Masalas",
      slug: "spices-masalas",
      icon: "Flame",
      image: "/images/products/everest_garam_masala.jpg",
      description: "Everest Garam Masala, MDH Deggi Mirch, Tata Salt, and whole blended spices.",
    },
    {
      name: "Dairy & Breakfast",
      slug: "dairy-breakfast",
      icon: "Coffee",
      image: "/images/products/amul_butter.jpg",
      description: "Amul pasteurized butter, cow ghee, toned milk, cheese slices, oats and breakfast cereals.",
    },
    {
      name: "Snacks & Beverages",
      slug: "snacks-beverages",
      icon: "GlassWater",
      image: "/images/products/sprite_bottle.jpg",
      description: "Chilled Sprite, Haldiram's Bhujia Sev, Maggi noodles, Lay's chips, and Tata tea.",
    },
    {
      name: "Personal Care & Cleaning",
      slug: "personal-care-cleaning",
      icon: "Sparkle",
      image: "/images/products/impact_wash.jpg",
      description: "Impact Wash detergent powder, Surf Excel, Vim gel, Dettol antiseptic, and soaps.",
    },
  ];

  const createdCategories: Record<string, string> = {};
  for (const cat of categoriesData) {
    const created = await prisma.category.create({ data: cat });
    createdCategories[cat.slug] = created.id;
  }

  // 2. Comprehensive Products Catalog with 100% Unique Product Photos
  const productsData = [
    // --- SNACKS & BEVERAGES ---
    {
      name: "Sprite Cold Drink Bottle",
      slug: "sprite-bottle-750ml",
      description: "Clear, crisp lemon-lime sparkling refreshing cold soda drink, served chilled.",
      price: 40,
      mrp: 45,
      stock: 180,
      unit: "750 ml",
      imageUrl: "/images/products/sprite_bottle.jpg",
      badge: "Chilled Special",
      isFeatured: true,
      isVegetarian: true,
      brand: "Coca-Cola",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Haldiram's Nagpur Bhujia Sev",
      slug: "haldirams-bhujia-sev-400g",
      description: "Crispy spiced moth bean flour noodle snack seasoned with authentic Indian herbs and spices.",
      price: 110,
      mrp: 125,
      stock: 140,
      unit: "400 g",
      imageUrl: "/images/products/haldirams_bhujia.jpg",
      badge: "Tea-Time Snack",
      isFeatured: true,
      isVegetarian: true,
      brand: "Haldiram's",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Maggi 2-Minute Masala Instant Noodles",
      slug: "maggi-masala-noodles-4pack",
      description: "Favorite classic instant noodles with the authentic aroma of roasted spices and herbs.",
      price: 56,
      mrp: 60,
      stock: 220,
      unit: "Pack of 4 (280 g)",
      imageUrl: "/images/products/maggi_noodles.svg",
      badge: "All-Time Favorite",
      isFeatured: true,
      isVegetarian: true,
      brand: "Nestle",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Lay's India's Magic Masala Potato Chips",
      slug: "lays-magic-masala-chips-50g",
      description: "Crispy crinkled potato chips infused with a blend of spicy, tangy Indian masalas.",
      price: 20,
      mrp: 20,
      stock: 160,
      unit: "50 g Pack",
      imageUrl: "/images/products/lays_chips.svg",
      badge: "Popular Snack",
      isFeatured: false,
      isVegetarian: true,
      brand: "Lay's",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Tata Tea Gold Leaf & Dust Blend",
      slug: "tata-tea-gold-500g",
      description: "Exquisite blend of fine Assam tea leaves with gently rolled 15% long leaves for rich aroma.",
      price: 295,
      mrp: 340,
      stock: 90,
      unit: "500 g",
      imageUrl: "/images/products/tata_tea_gold.svg",
      badge: "Rich Taste",
      isFeatured: true,
      isVegetarian: true,
      brand: "Tata Tea",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Cadbury Dairy Milk Silk Chocolate Bar",
      slug: "cadbury-dairy-milk-silk-150g",
      description: "Smoother, creamier, and melt-in-mouth milk chocolate bar for sweet celebrations.",
      price: 175,
      mrp: 185,
      stock: 85,
      unit: "150 g",
      imageUrl: "/images/products/cadbury_silk.svg",
      badge: "Sweet Treat",
      isFeatured: false,
      isVegetarian: true,
      brand: "Cadbury",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Parle-G Gold Glucose Biscuits Mega Pack",
      slug: "parle-g-gold-biscuits-1kg",
      description: "Bigger, crisper, and richer glucose biscuits, trusted across millions of Indian homes.",
      price: 90,
      mrp: 100,
      stock: 130,
      unit: "1 kg Pack",
      imageUrl: "/images/products/parle_g.svg",
      badge: "Daily Chai Companion",
      isFeatured: false,
      isVegetarian: true,
      brand: "Parle",
      categoryId: createdCategories["snacks-beverages"],
    },
    {
      name: "Frooti Fresh Mango Drink",
      slug: "frooti-mango-drink-1-2l",
      description: "Made from real ripe Totapuri mangoes, delicious thirst-quenching refreshing mango drink.",
      price: 65,
      mrp: 75,
      stock: 110,
      unit: "1.2 L Bottle",
      imageUrl: "/images/products/frooti.svg",
      badge: "Refreshing",
      isFeatured: false,
      isVegetarian: true,
      brand: "Parle Agro",
      categoryId: createdCategories["snacks-beverages"],
    },

    // --- DAIRY & BREAKFAST ---
    {
      name: "Amul Butter (Pasteurized)",
      slug: "amul-butter-500g",
      description: "Utterly butterly delicious creamy salted table butter made from fresh dairy milk.",
      price: 275,
      mrp: 290,
      stock: 65,
      unit: "500 g",
      imageUrl: "/images/products/amul_butter.jpg",
      badge: "Breakfast Star",
      isFeatured: true,
      isVegetarian: true,
      brand: "Amul",
      categoryId: createdCategories["dairy-breakfast"],
    },
    {
      name: "Amul Taaza Homogenised Toned Milk",
      slug: "amul-taaza-toned-milk-1l",
      description: "Pure and fresh toned milk with 3.0% fat, sterilized and packed in tamper-proof aseptic pack.",
      price: 72,
      mrp: 75,
      stock: 95,
      unit: "1 L Tetra Pack",
      imageUrl: "/images/products/amul_taaza_milk.svg",
      badge: "Fresh Dairy",
      isFeatured: true,
      isVegetarian: true,
      brand: "Amul",
      categoryId: createdCategories["dairy-breakfast"],
    },
    {
      name: "Amul Processed Cheese Slices",
      slug: "amul-cheese-slices-200g",
      description: "10 individually wrapped delicious creamy processed cheese slices for sandwiches and burgers.",
      price: 140,
      mrp: 155,
      stock: 70,
      unit: "10 Slices (200 g)",
      imageUrl: "/images/products/amul_cheese.svg",
      badge: "Kids Favorite",
      isFeatured: false,
      isVegetarian: true,
      brand: "Amul",
      categoryId: createdCategories["dairy-breakfast"],
    },
    {
      name: "Quaker Rolled White Oats",
      slug: "quaker-rolled-oats-1kg",
      description: "100% whole grain nutritious breakfast oats, high in dietary fiber to support heart health.",
      price: 185,
      mrp: 220,
      stock: 55,
      unit: "1 kg Pouch",
      imageUrl: "/images/products/quaker_oats.svg",
      badge: "Healthy Choice",
      isFeatured: false,
      isVegetarian: true,
      brand: "Quaker",
      categoryId: createdCategories["dairy-breakfast"],
    },
    {
      name: "Kellogg's Real Almond & Honey Corn Flakes",
      slug: "kelloggs-corn-flakes-almond-honey-475g",
      description: "Crispy golden corn flakes enriched with real Californian almonds and sweet floral honey.",
      price: 245,
      mrp: 285,
      stock: 45,
      unit: "475 g Box",
      imageUrl: "/images/products/kelloggs_cornflakes.svg",
      badge: "Crunchy Breakfast",
      isFeatured: false,
      isVegetarian: true,
      brand: "Kellogg's",
      categoryId: createdCategories["dairy-breakfast"],
    },

    // --- PERSONAL CARE & CLEANING ---
    {
      name: "Impact Wash Premium Detergent Powder",
      slug: "impact-wash-detergent-2kg",
      description: "Advanced active enzyme formula that removes tough collar stains while keeping clothes vibrant.",
      price: 199,
      mrp: 240,
      stock: 85,
      unit: "2 kg Pack",
      imageUrl: "/images/products/impact_wash.jpg",
      badge: "In-Store Banner Deal",
      isFeatured: true,
      isVegetarian: true,
      brand: "Impact Wash",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Surf Excel Easy Wash Detergent Powder",
      slug: "surf-excel-easy-wash-1kg",
      description: "Formulated with 10 hands power to effortlessly wash dirt and curry stains in minutes.",
      price: 145,
      mrp: 160,
      stock: 120,
      unit: "1 kg Pack",
      imageUrl: "/images/products/surf_excel.svg",
      badge: "Top Seller",
      isFeatured: true,
      isVegetarian: true,
      brand: "Surf Excel",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Vim Lemon Dishwash Gel Bottle",
      slug: "vim-lemon-dishwash-gel-750ml",
      description: "Concentrated gel with 100 lemons power, degreases oily pots and stainless steel utensils effortlessly.",
      price: 135,
      mrp: 155,
      stock: 90,
      unit: "750 ml Bottle",
      imageUrl: "/images/products/vim_gel.svg",
      badge: "Kitchen Care",
      isFeatured: false,
      isVegetarian: true,
      brand: "Vim",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Harpic Power Plus 10X Toilet Cleaner",
      slug: "harpic-power-plus-1l",
      description: "Thick blue liquid formula eliminates 99.9% germs, limescale, and tough yellowish stains.",
      price: 180,
      mrp: 205,
      stock: 75,
      unit: "1 L Bottle",
      imageUrl: "/images/products/harpic.svg",
      badge: "Hygiene Shield",
      isFeatured: false,
      isVegetarian: true,
      brand: "Harpic",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Dettol Original Antiseptic Disinfectant Liquid",
      slug: "dettol-antiseptic-liquid-550ml",
      description: "Trusted germ protection for first aid, wound cleaning, personal hygiene, and laundry sanitizer.",
      price: 195,
      mrp: 220,
      stock: 80,
      unit: "550 ml Bottle",
      imageUrl: "/images/products/dettol.svg",
      badge: "Doctor Recommended",
      isFeatured: false,
      isVegetarian: true,
      brand: "Dettol",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Colgate MaxFresh Peppermint Ice Gel Toothpaste",
      slug: "colgate-maxfresh-peppermint-150g",
      description: "Infused with cooling crystals for 10x longer lasting fresh breath and cavity protection.",
      price: 98,
      mrp: 110,
      stock: 140,
      unit: "150 g Pack",
      imageUrl: "/images/products/colgate.svg",
      badge: "Fresh Breath",
      isFeatured: false,
      isVegetarian: true,
      brand: "Colgate",
      categoryId: createdCategories["personal-care-cleaning"],
    },
    {
      name: "Dove Cream Beauty Bathing Soap (3-Pack)",
      slug: "dove-cream-beauty-soap-300g",
      description: "Enriched with 1/4th moisturizing cream to nourish dry skin soft and glowing.",
      price: 165,
      mrp: 190,
      stock: 65,
      unit: "3 x 100 g Bars",
      imageUrl: "/images/products/dove_soap.svg",
      badge: "Gentle Care",
      isFeatured: false,
      isVegetarian: true,
      brand: "Dove",
      categoryId: createdCategories["personal-care-cleaning"],
    },

    // --- SPICES & CONDIMENTS ---
    {
      name: "Everest Garam Masala",
      slug: "everest-garam-masala-100g",
      description: "Celebrated blend of 13 aromatic Indian spices to give curries their rich royal aroma.",
      price: 88,
      mrp: 96,
      stock: 150,
      unit: "100 g",
      imageUrl: "/images/products/everest_garam_masala.jpg",
      badge: "Essential",
      isFeatured: true,
      isVegetarian: true,
      brand: "Everest",
      categoryId: createdCategories["spices-masalas"],
    },
    {
      name: "MDH Deggi Mirch (Kashmiri Blend)",
      slug: "mdh-deggi-mirch-100g",
      description: "Produces deep crimson red gravy color with balanced mild pleasant spiciness.",
      price: 92,
      mrp: 100,
      stock: 130,
      unit: "100 g",
      imageUrl: "/images/products/mdh_deggi_mirch.jpg",
      badge: "Hot Deal",
      isFeatured: true,
      isVegetarian: true,
      brand: "MDH",
      categoryId: createdCategories["spices-masalas"],
    },
    {
      name: "Tata Salt Vacuum Evaporated Iodized Salt",
      slug: "tata-salt-iodized-1kg",
      description: "India's most trusted pure white iodized salt for daily mental and physical wellness.",
      price: 26,
      mrp: 28,
      stock: 250,
      unit: "1 kg Pack",
      imageUrl: "/images/products/tata_salt.svg",
      badge: "Daily Essential",
      isFeatured: true,
      isVegetarian: true,
      brand: "Tata",
      categoryId: createdCategories["spices-masalas"],
    },
    {
      name: "Kissan Fresh Tomato Ketchup",
      slug: "kissan-tomato-ketchup-950g",
      description: "100% real juicy vine-ripened tomatoes made into sweet and tangy family sauce.",
      price: 125,
      mrp: 145,
      stock: 85,
      unit: "950 g Squeezy Bottle",
      imageUrl: "/images/products/kissan_ketchup.svg",
      badge: "Family Pack",
      isFeatured: false,
      isVegetarian: true,
      brand: "Kissan",
      categoryId: createdCategories["spices-masalas"],
    },
    {
      name: "Catch Black Pepper Table Sprinkler",
      slug: "catch-black-pepper-sprinkler-100g",
      description: "Coarsely ground Malabar black pepper in a convenient rotating tabletop shaker.",
      price: 85,
      mrp: 95,
      stock: 60,
      unit: "100 g Can",
      imageUrl: "/images/products/catch_pepper.svg",
      badge: "Pungent Aroma",
      isFeatured: false,
      isVegetarian: true,
      brand: "Catch",
      categoryId: createdCategories["spices-masalas"],
    },

    // --- EDIBLE OILS & GHEE ---
    {
      name: "Bail Kolhu Kacchi Ghani Mustard Oil",
      slug: "bail-kolhu-mustard-oil-1l",
      description: "100% pure cold-pressed sarson tel with authentic pungent punch and natural antioxidants.",
      price: 148,
      mrp: 170,
      stock: 140,
      unit: "1 L Bottle",
      imageUrl: "/images/products/bail_kolhu_oil.jpg",
      badge: "Naugarh Favorite",
      isFeatured: true,
      isVegetarian: true,
      brand: "Bail Kolhu",
      categoryId: createdCategories["edible-oils-ghee"],
    },
    {
      name: "Amul Pure Cow Ghee",
      slug: "amul-pure-cow-ghee-1l",
      description: "Rich, granular golden cow ghee made from fresh cream, offering traditional aroma and flavor.",
      price: 610,
      mrp: 650,
      stock: 55,
      unit: "1 L Tin",
      imageUrl: "/images/products/amul_pure_ghee.jpg",
      badge: "Pure & Fresh",
      isFeatured: true,
      isVegetarian: true,
      brand: "Amul",
      categoryId: createdCategories["edible-oils-ghee"],
    },
    {
      name: "Fortune Sunlite Refined Sunflower Oil",
      slug: "fortune-sunflower-oil-1l",
      description: "Light, healthy, and easy-to-digest refined cooking oil enriched with Vitamin A and D.",
      price: 135,
      mrp: 155,
      stock: 110,
      unit: "1 L Pouch",
      imageUrl: "/images/products/fortune_sunflower_oil.svg",
      badge: "Heart Healthy",
      isFeatured: false,
      isVegetarian: true,
      brand: "Fortune",
      categoryId: createdCategories["edible-oils-ghee"],
    },

    // --- DALS & PULSES ---
    {
      name: "Tata Sampann Unpolished Toor Dal",
      slug: "tata-sampann-unpolished-toor-dal-1kg",
      description: "Rich in natural protein, delicious unpolished arhar dal with no artificial polish or coloring.",
      price: 168,
      mrp: 195,
      stock: 110,
      unit: "1 kg",
      imageUrl: "/images/products/tata_toor_dal.jpg",
      badge: "15% OFF",
      isFeatured: true,
      isVegetarian: true,
      brand: "Tata Sampann",
      categoryId: createdCategories["dals-pulses"],
    },
    {
      name: "Premium Yellow Moong Dal (Dhuli)",
      slug: "premium-yellow-moong-dal-1kg",
      description: "Quick cooking, light and wholesome yellow split moong dal, thoroughly cleaned.",
      price: 135,
      mrp: 155,
      stock: 75,
      unit: "1 kg",
      imageUrl: "/images/products/moong_dal.svg",
      badge: null,
      isFeatured: false,
      isVegetarian: true,
      brand: "Tata Sampann",
      categoryId: createdCategories["dals-pulses"],
    },
    {
      name: "Desi Chana Dal Unpolished",
      slug: "desi-chana-dal-1kg",
      description: "Sweet and nutty chana dal, high dietary fiber, perfect for puran poli and tadka dal.",
      price: 115,
      mrp: 130,
      stock: 65,
      unit: "1 kg",
      imageUrl: "/images/products/chana_dal.svg",
      badge: null,
      isFeatured: false,
      isVegetarian: true,
      brand: "Tata Sampann",
      categoryId: createdCategories["dals-pulses"],
    },
    {
      name: "Tata Sampann Organic Kabuli Chana",
      slug: "tata-sampann-kabuli-chana-1kg",
      description: "Large, uniform white chickpeas perfect for rich Punjabi chole and Amritsari bhature.",
      price: 155,
      mrp: 180,
      stock: 70,
      unit: "1 kg",
      imageUrl: "/images/products/tata_kabuli_chana.svg",
      badge: "Punjabi Chole Special",
      isFeatured: false,
      isVegetarian: true,
      brand: "Tata Sampann",
      categoryId: createdCategories["dals-pulses"],
    },

    // --- RICE & GRAINS & DRY FRUITS ---
    {
      name: "India Gate Basmati Rice Feast Rozzana",
      slug: "india-gate-basmati-rice-5kg",
      description: "Aromatic, long grain basmati rice specially aged for daily festive dining and biryanis.",
      price: 440,
      mrp: 520,
      stock: 60,
      unit: "5 kg",
      imageUrl: "/images/products/india_gate_rice.jpg",
      badge: "Super Saver",
      isFeatured: true,
      isVegetarian: true,
      brand: "India Gate",
      categoryId: createdCategories["rice-grains"],
    },
    {
      name: "Daawat Super Basmati Rice",
      slug: "daawat-super-basmati-rice-1kg",
      description: "Slender and pearly grains with distinct aroma, expands up to 2.5 times when cooked.",
      price: 165,
      mrp: 190,
      stock: 85,
      unit: "1 kg",
      imageUrl: "/images/products/daawat_rice.svg",
      badge: null,
      isFeatured: false,
      isVegetarian: true,
      brand: "Daawat",
      categoryId: createdCategories["rice-grains"],
    },
    {
      name: "Tata Sampann High Fiber Thick Poha",
      slug: "tata-sampann-thick-poha-500g",
      description: "Hygienically flattened paddy flakes that make fluffy, non-sticky morning kanda batata poha.",
      price: 48,
      mrp: 55,
      stock: 120,
      unit: "500 g",
      imageUrl: "/images/products/tata_poha.svg",
      badge: "Quick Breakfast",
      isFeatured: false,
      isVegetarian: true,
      brand: "Tata Sampann",
      categoryId: createdCategories["rice-grains"],
    },
    {
      name: "Premium California Crunchy Almonds (Badam)",
      slug: "california-badam-almonds-500g",
      description: "100% natural, whole crunchy Californian almonds rich in Vitamin E, magnesium, and proteins.",
      price: 460,
      mrp: 550,
      stock: 50,
      unit: "500 g Pouch",
      imageUrl: "/images/products/california_badam.svg",
      badge: "Brain Power",
      isFeatured: true,
      isVegetarian: true,
      brand: "Grocery For All Select",
      categoryId: createdCategories["rice-grains"],
    },
    {
      name: "Whole W240 King Cashew Nuts (Kaju)",
      slug: "king-cashew-nuts-kaju-500g",
      description: "Jumbo, whole white cashews with rich buttery taste, ideal for kheer, sweets, and snacking.",
      price: 490,
      mrp: 590,
      stock: 45,
      unit: "500 g Pouch",
      imageUrl: "/images/products/king_kaju.svg",
      badge: "Premium Quality",
      isFeatured: false,
      isVegetarian: true,
      brand: "Grocery For All Select",
      categoryId: createdCategories["rice-grains"],
    },

    // --- ATTA, FLOURS & SOOJI ---
    {
      name: "Pohsan Fine Maida",
      slug: "pohsan-fine-maida-1kg",
      description: "Super fine wheat flour ideal for crispy samosas, bhature, cakes, and bakery delicacies.",
      price: 45,
      mrp: 52,
      stock: 120,
      unit: "1 kg",
      imageUrl: "/images/products/pohsan_maida.jpg",
      badge: "In-Store Favorite",
      isFeatured: true,
      isVegetarian: true,
      brand: "Pohsan",
      categoryId: createdCategories["atta-flours-sooji"],
    },
    {
      name: "Pohsan Crispy Sooji (Rawa)",
      slug: "pohsan-crispy-sooji-500g",
      description: "Premium granular semolina for delicious halwa, upma, and crispy idli/dosa batter.",
      price: 35,
      mrp: 40,
      stock: 95,
      unit: "500 g",
      imageUrl: "/images/products/pohsan_sooji.jpg",
      badge: "Best Seller",
      isFeatured: true,
      isVegetarian: true,
      brand: "Pohsan",
      categoryId: createdCategories["atta-flours-sooji"],
    },
    {
      name: "Aashirvaad Shudh Chakki Atta",
      slug: "aashirvaad-shudh-chakki-atta-5kg",
      description: "100% pure whole wheat flour processed with traditional chakki grinding for extra soft rotis.",
      price: 245,
      mrp: 275,
      stock: 80,
      unit: "5 kg",
      imageUrl: "/images/products/aashirvaad_atta.jpg",
      badge: "Top Value",
      isFeatured: true,
      isVegetarian: true,
      brand: "Aashirvaad",
      categoryId: createdCategories["atta-flours-sooji"],
    },
    {
      name: "Fortune Pure Chana Besan",
      slug: "fortune-chana-besan-500g",
      description: "Finely ground pure gram flour for crispy pakoras, sweets, kadhi, and savoury delicacies.",
      price: 58,
      mrp: 68,
      stock: 85,
      unit: "500 g",
      imageUrl: "/images/products/fortune_besan.svg",
      badge: null,
      isFeatured: false,
      isVegetarian: true,
      brand: "Fortune",
      categoryId: createdCategories["atta-flours-sooji"],
    },
  ];

  for (const prod of productsData) {
    await prisma.product.create({ data: prod });
  }

  // 3. Coupons
  const coupons = [
    {
      code: "WELCOME100",
      discountPercent: 15,
      minOrderAmount: 499,
      maxDiscount: 100,
      description: "Get 15% OFF up to ₹100 on your first grocery order!",
      isActive: true,
    },
    {
      code: "SUPERKIRANA",
      discountPercent: 20,
      minOrderAmount: 999,
      maxDiscount: 250,
      description: "Super Market Special: 20% OFF up to ₹250 on orders above ₹999",
      isActive: true,
    },
    {
      code: "FREESHIP",
      discountPercent: 10,
      minOrderAmount: 299,
      maxDiscount: 50,
      description: "Instant ₹50 savings on any delivery in Naugarh / Tetari Bazar",
      isActive: true,
    },
  ];

  for (const c of coupons) {
    await prisma.coupon.create({ data: c });
  }

  // 4. Sample Customers
  const customer1 = await prisma.customer.create({
    data: {
      name: "Rajesh Verma",
      phone: "9838012345",
      password: "123456",
      email: "rajesh.verma@example.com",
      address: "House 42, Tetari Bazar Main Road",
      city: "Naugarh",
      pincode: "272207",
      points: 50,
    },
  });

  const customer2 = await prisma.customer.create({
    data: {
      name: "Pooja Srivastava",
      phone: "9792067890",
      password: "123456",
      email: "pooja.sri@example.com",
      address: "Plot 18, Rahul Nagar, Near Grocery For All",
      city: "Naugarh",
      pincode: "272207",
      points: 50,
    },
  });

  // 5. Initial Sample Orders
  await prisma.order.create({
    data: {
      orderNumber: "GFA-8021",
      customerId: customer1.id,
      customerName: customer1.name,
      customerPhone: customer1.phone,
      customerAddress: `${customer1.address}, ${customer1.city} - ${customer1.pincode}`,
      status: "DELIVERED",
      paymentMethod: "UPI",
      paymentStatus: "PAID",
      subtotal: 1040,
      deliveryFee: 0,
      discount: 100,
      total: 940,
      deliverySlot: "Morning (9 AM - 11 AM)",
      notes: "Please call upon arrival at gate.",
      items: {
        create: [
          {
            productName: "Aashirvaad Shudh Chakki Atta",
            productImage: "/images/products/aashirvaad_atta.jpg",
            price: 245,
            quantity: 2,
            unit: "5 kg",
          },
          {
            productName: "Bail Kolhu Kacchi Ghani Mustard Oil",
            productImage: "/images/products/bail_kolhu_oil.jpg",
            price: 148,
            quantity: 2,
            unit: "1 L Bottle",
          },
          {
            productName: "Tata Sampann Unpolished Toor Dal",
            productImage: "/images/products/tata_toor_dal.jpg",
            price: 168,
            quantity: 1,
            unit: "1 kg",
          },
          {
            productName: "Sprite Cold Drink Bottle",
            productImage: "/images/products/sprite_bottle.jpg",
            price: 40,
            quantity: 2,
            unit: "750 ml",
          },
        ],
      },
    },
  });

  console.log("✅ Seed completed: Every product has its own unique, authentic packaging image!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
